
service: sms-notification

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  stage: dev
  region: us-east-1

functions:
  stream_listener:
    handler: handler.send
    role: ${ssm:${self:custom.stage}-sms-iam-role}
    events:
      - sqs: ${ssm:${self:custom.stage}-sms-sqs}
    environment:
      PHONE_FROM: ${ssm:${self:custom.stage}-sms-phone-from}
      PHONE_TO: ${ssm:${self:custom.stage}-sms-phone-to}
      TWILIO_ACCOUNT: ${ssm:${self:custom.stage}-twilio-account}
      TWILIO_API_KEY: ${ssm:${self:custom.stage}-twilio-api-key}

custom:
  stage: ${opt:stage, self:provider.stage}