service: api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  stage: dev
  region: us-east-1


functions:
  register:
    role: ${ssm:${self:custom.stage}-register-iam-role}
    handler: register/handler.register
    events:
      - httpApi:
          path: /users
          method: post
    environment:
      DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}

  login:
    role: ${ssm:${self:custom.stage}-login-iam-role}
    handler: login/handler.login
    events:
      - httpApi:
          path: /login
          method: post
    environment:
      DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}
      JWT_SECRET: ${ssm:${self:custom.stage}-jwt-secret}
      EMAIL_GSI: ${ssm:${self:custom.stage}-email-gsi}

custom:
  stage: ${opt:stage, self:provider.stage}