service: api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  stage: dev
  region: us-east-1


  environment:
    DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}


functions:
  hello:
    handler: register/handler.register
    events:
      - httpApi:
          path: /users
          method: post
custom:
  stage: ${opt:stage, self:provider.stage}